### ISSUE TITLE
Ordering (adaptive/non-adaptive)

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/pdc#1]
Marco could you please check if what I did is correct for adaptive/non-adaptive greedy? I'm guessing there is a smarter to do this? Could you please check? The code is in r/order.R and the part to check is below:

```
if (adaptive == TRUE){
      w <- as.vector(abs(solve(t(sX)%*%sX,t(sX)%*%y0)))
      norm.col <- as.vector(sqrt(t(rep(1,n))%*%sX^2))
      wX <- X%*%diag(w/norm.col)
   }else{
   wX <- X
}
```

**Comment by marcoavella** [comment]
Looks fine to me. The scaling can be done with the function scale. It won't make a big difference unless n and p are very large.

**Comment by stephaneguerrier** [comment]
OK, thanks!
